# Generated by Django 4.0.6 on 2022-08-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_pic',
            field=models.CharField(default='', max_length=200),
        ),
    ]
