# Generated by Django 4.0.6 on 2022-08-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author_pic'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['date'], name='blog_blog_date_bc9b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['hot'], name='blog_blog_hot_5aaff6_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title'], name='blog_blog_title_d6be1d_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['article'], name='blog_blog_article_45e4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['public_date'], name='blog_commen_public__f18966_idx'),
        ),
    ]
