# Generated by Django 4.0.6 on 2022-09-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_tag_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag_list',
            field=models.TextField(default=''),
        ),
    ]
