# Generated by Django 4.0.6 on 2022-09-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_tag_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='c1_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='c2_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='else_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='java_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='javascript_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='php_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='python_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='sql_tag',
            field=models.BooleanField(default=False),
        ),
    ]
